### ISSUE TITLE
Pipectl does not exit after downstream process ends

### ISSUE THREAD

**Issue by Vladimir-csp** [Ferdi265/pipectl#1] opened 2024-05-14 21:17 UTC
If nothing was sent, pipectl exits.

```
$ pipectl -n test -o | sh -c 'while read -r line ; do echo "got $line" ; done' &
[1] 1791324
$ kill $!
$ ps -o cmd
CMD
ps -o cmd
/bin/bash
```
If something was sent, pipectl lingers even after downstream process ends.
```
$ pipectl -n test -o | sh -c 'while read -r line ; do echo "got $line" ; done' &
[1] 1797840
$ echo something | pipectl -n test -i
got something
$ kill $!
$ ps -o cmd
CMD
pipectl -n test -o
ps -o cmd
/bin/bash
```

**Comment by Ferdi265** [comment] 2024-06-24 18:22
Currently debugging this: the issue is that when writing data to the pipe it seems that  `pipe_data()` never returns. The first read correctly returns the data, which is also correctly written to stdout, but the second read hangs.

That code looks very incorrect to me in general, since this loses bytes if the write returns early, and isn't how poll is supposed to be used (read once after poll says data is ready, don't attempt to read multiple times).

The whole piping code needs to be rewritten to have a persistent buffer and correctly use poll, so that no bytes are lost and execution correctly returns to the event loop after each attempted read or write.

I'm honestly astonished this ever worked this reliably in the first place and only broke on the output process dying.

**Comment by Ferdi265** [comment] 2024-06-24 18:25
planned to be fixed in 0.5.0 (minor release instead of a bugfix release since this is a major change in the piping code)

**Comment by Ferdi265** [comment] 2024-06-24 23:45
Should be fixed as of 695c059. I'm holding off on releasing this for a few days to let this settle and see if I didn't break this completely. It looks like it's working correctly in local testing.

**Comment by Ferdi265** [comment] 2024-06-24 23:57
Reworked this in 740b463, now split into several commits for clarity.

Pushing this directly onto main so fast might not have been the best idea, sorry for the force push.

**Comment by Ferdi265** [comment] 2024-06-25 08:45
I appear to have broken the fix. It's not working anymore today. I shouldn't work that late at night

**Closed as completed** 2024-06-25 08:57 UTC
Labels: bug

**Comment by Ferdi265** [comment] 2024-06-25 08:59
I seem to have accidently removed part of the initialization code of the pipe buffers in the rebase. Works again.
